### ISSUE TITLE
[Airbrake] [Staging] undefined method `each_node' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#868] opened 2016-03-23 11:16 UTC
**Airbrake error:** [#6710](https://quintel.airbrake.io/projects/111227/groups/1647755463877966710)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `undefined method `each_node' for nil:NilClass`
**Occurred at:** Mar 23, 2016 11:08:22 UTC
**First seen at:** Mar 23, 2016 11:08:18 UTC
**Occurrences:** 2 (2 since last deploy on Mar 23, 2016 09:08:12 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/179](https://beta-moses.energytransitionmodel.com/testing_grounds/179)
**File:** `[PROJECT_ROOT]/app/helpers/testing_grounds_helper.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/helpers/testing_grounds_helper.rb:53:in options_for_stakeholders
[PROJECT_ROOT]/app/views/testing_grounds/show.html.haml:118:in _app_views_testing_grounds_show_html_haml___370906246315284047_69989930156060
[GEM_ROOT]/gems/actionview-4.1.8/lib/action_view/template.rb:145:in block in render
[GEM_ROOT]/gems/activesupport-4.1.8/lib/active_support/notifications.rb:161:in instrument
```

**Comment by grdw** [comment] 2016-04-15 14:57
Topology of the LES is set to nil :disappointed:  This should not even be possible in the first place. Even after you remove a topology, the topology should still be 'present' but 'orphaned'. I'm guessing that somebody removed the topology it directly from the database OR the user in question was able to pass a nil value from the chrome/firefox console and submitted the form.

**Comment by grdw** [comment] 2016-06-16 13:09
I'm closing this issue due to the unlikelyhood of this ever happening again. It's also not reproduceable without mingling with the database.

**Comment by dennisschoenmakers** [comment] 2016-07-28 17:22
*Comment from Airbrake:* Resolved [error](https://quintel.airbrake.io/projects/111227/groups/1647755463877966710) reoccurred.

**Closed** 2016-07-28 17:26 UTC
Labels: airbrake
