### ISSUE TITLE
switching concurrency leads to errors

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1145] opened 2016-06-27 09:35 UTC
In a working LES [(#549)](https://beta-moses.energytransitionmodel.com/testing_grounds/549/) I switched concurrency of buildings and households to minimal.
This resulted in a LES that can not be calculated. Screenshot is shown below.

Switching back to max buildings concurrency does not reset the initial technology profile, but also  results in a LES that can not be calculated.

The same applies when I change the concurrency of households. I have not yet  tried other changing the concurrency of other technologies.

The initial, working, technology profile can be found in the "Ameland" folder in Dropbox. It is named _"TP concurrency bug.csv"_.

![image](https://cloud.githubusercontent.com/assets/19907658/16374613/86d48a76-3c57-11e6-8de7-a9a5e67c3a9b.png)

@dennisschoenmakers

**Comment by ChaelKruip** [comment] 2016-06-27 13:48
> In a working LES (#549)

For many technologies, the number of units is zero in this LES. I can imagine that the concurrency calculation has trouble dealing with this. Perhaps you could try to remove all of those technologies from the LES and try again? I have confirmed that in a simpler LES the concurrency settings work as expected and result in valid output.

**Comment by DorinevanderVlies** [comment] 2016-06-28 07:31
Sounds plausible. But I don't think that is the problem.

I have tried again on [LES 553](https://beta-moses.energytransitionmodel.com/testing_grounds/553).
This LES does not contain any technologies with number of units 0.

For any change in concurrency I end up with a LES that cannot be calculated.

**Example**
I set all the PV units to 1. When I change the concurrency of PV to min. Several other technologies are split up and the scenario that is created "could not be calculated".

**Comment by ChaelKruip** [comment] 2016-06-28 13:44
> I set all the PV units to 1. When I change the concurrency of PV to min. Several other technologies are split up and the scenario that is created "could not be calculated".

I can confirm that his happens. Weird that the PV concurrency slider has impact on the other technologies. @antw can you look into this?

**Comment by grdw** [comment] 2016-07-06 08:48
I took some time to investigate it a little. 

I tested the following LES's on 'beta':

*With one technology/buffer at one endpoint*:

- A Les with one technology, switching concurrency from min to max with unit > 1. This seems to be working ok. I used one EV/Base load. I don't experience any problems with the calculation. I do see that the demand is empty when adding a new base load but I think this is how it's supposed to work? ( @ChaelKruip )
- A Les with one technology type, one buffer type with one technology attached to that one buffer (with all units > 1). This seems to working ok except for [this issue](https://github.com/quintel/etmoses/issues/1170). The buffer and boosting radio buttons are  blanked.

*With technologies/buffers at multiple endpoints*:

- A Les with one technology, switching concurrency from min to max with unit > 1, attached to two endpoints. This seems to be working ok. 
-  A Les with one technology type, one buffer type with one technology attached to the buffer (with all units > 1), attached to two end-points.*

*The weird thing is, that in that situation I have technologies that are detached from their respected buffers but the calculation somehow still continues. Probably attaching those technologies to buffers that are not at the correct end-point? 

*Not removing any technologies, keeping everything standard*:
Minimizing concurrency for *all technologies* becomes a horrible pain at that moment 😞 my browser freezes for a moment, than when it does come back you can't seem to be able to save your results. It will give a ` [HTTP/1.1 413 Request Entity Too Large 5027ms]`. So hmmm

**Comment by grdw** [comment] 2016-07-06 08:53
I'm still not sure if that's what you are experiencing. So maybe you could show me what the problems are that you experienced? @DorinevanderVlies

**Comment by antw** [comment] 2016-07-06 09:15
Here's the scenario I've been using to try to reproduce this: [beta LES-585](https://beta-moses.energytransitionmodel.com/testing_grounds/585). It has a fairly normal distribution of technologies on one endpoint.

What I found so far is that if I edit the LES and set solar PV concurrency to "min" and hit "Apply" everything seems to work fine. However, if I add a solar PV array to "Endpoint 2" and then change the concurrency setting, the heating technologies on "Endpoint 1" are split up. It seems half the heating technologies are assigned to a non-existent `space_heating_buffer_2`.

I think what it's trying to do is split the heating technologies across the two endpoints (which shouldn't happen).

**Comment by Sanne512** [comment] 2016-07-30 13:54
I'm including @JeroenvdLogt

**Closed** 2016-08-24 09:15 UTC
Labels: Being pulled, Bug, Priority
