### ISSUE TITLE
Gas-load charts do not load for the LESses I have tried

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1050] opened 2016-06-08 08:49 UTC
For instance: [https://beta-moses.energytransitionmodel.com/testing_grounds/499/gas_load](https://beta-moses.energytransitionmodel.com/testing_grounds/499/gas_load)

![etmoses](https://cloud.githubusercontent.com/assets/1303760/15888282/8cc7b6ba-2d66-11e6-93ca-00fc615301ee.png)

**Comment by antw** [comment] 2016-06-09 08:14
The HTTP request times out because the LES takes too long to calculate. We'll need to switch this page to use a poller. I think this is related to #1017.

**Comment by Sanne512** [comment] 2016-07-12 11:58
What's the status?

**Comment by ChaelKruip** [comment] 2016-07-12 14:30
> What's the status?

This will be picked up in the current sprint. I have increased its priority but it would still be useful to know if you need this at a certain time.

**Comment by Sanne512** [comment] 2016-07-15 11:56
@JeroenvdLogt @ThomBuijs Do you need this for a certain time?

**Comment by ThomBuijs** [comment] 2016-08-01 11:31
Preferably, I would like this as soon as possible, since I will work on a use case which will include electricity, gas, and heat. Heat will still be in beta, so I would like to focus on electricity and gas for the moment and continue with heat as soon as it will be available on the live server. What would you advice?

**Comment by ChaelKruip** [comment] 2016-08-01 11:34
> Preferably, I would like this as soon as possible

We expect to have this working (on BETA) today. 

@antw is the gas-chart something that can be cherry-picked to LIVE easily so @ThomBuijs can work on electricity and gas in the LIVE server and heat networks can still be tested more on BETA?

**Comment by antw** [comment] 2016-08-01 12:40
The yearly gas flow chart fixes will be on beta momentarily. I'll see what I can do about getting it onto the live server...

**Comment by antw** [comment] 2016-08-01 13:41
> I'll see what I can do about getting it onto the live server...

I don't think this is possible. There are too many changes to the inner-workings of the charts, and those changes are mixed into commits involving heat. It's all or nothing. 😞

**Comment by ChaelKruip** [comment] 2016-08-01 13:43
> I don't think this is possible. There are too many changes to the inner-workings of the charts, and those changes are mixed into commits involving heat. It's all or nothing. 😞

Thanks @antw for your assessment!

**Comment by ThomBuijs** [comment] 2016-08-11 15:37
I was wondering what the status is of this issue. What does 

> grdw added a commit that referenced this issue a day ago 

mean?

**Comment by antw** [comment] 2016-08-11 15:44
> What does "grdw added a commit that referenced this issue a day ago" mean?

You can ignore that; it means some piece of code was changed, and that the change had something to do with this issue. In this case, the change was [actually made ten days ago](https://github.com/quintel/etmoses/issues/1050#ref-commit-5ed3338).

The issue has been fixed, and the changes are on the beta server already; it should now be possible to view the weekly gas load charts and annual gas flow charts for all LESes. It it not yet available on the live/production server since it depends on certain features which were added to accommodate the heat network.

**Comment by ThomBuijs** [comment] 2016-08-12 13:17
The yearly gas flow doesn't seem to work anymore in my LES [https://beta-moses.energytransitionmodel.com/testing_grounds/675/gas_load](url). I have seen it when you mentioned it was fixed, but right now it seems to stop working. My LES has only 10 households  so it is not that big.

**Comment by grdw** [comment] 2016-08-12 13:38
The error you are receiving (which is a little vague) does not have to do with the original issue. The problem is in #1371 . Therefor I'm closing this issue and will copy your comment over to that issue to keep github issue a bit cleaner.

**Closed by grdw** 2016-08-12 13:38 UTC
Labels: Bug
