### ISSUE TITLE
[Airbrake] [Production] Validation failed: Technology profile includes a connection to missing node "Woning 101d"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1424] opened 2016-09-13 11:33 UTC
**Airbrake error:** [#8293](https://quintel.airbrake.io/projects/111227/groups/1773874976850948293)
**Airbrake project:** ETMoses

**Error type:** `ActiveRecord::RecordInvalid`
**Error message:** `` Validation failed: Technology profile includes a connection to missing node "Woning 101d" ``
**Where:** `testing_grounds#save_as`
**Occurred at:** Sep 13, 2016 11:32:37 UTC
**First seen at:** Sep 13, 2016 11:32:37 UTC
**Occurrences:** 1 (1 since last deploy on Sep 13, 2016 09:59:10 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/549/save_as](https://moses.energytransitionmodel.com/testing_grounds/549/save_as)
**File:** `[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/validations.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/validations.rb:57:in save!
[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/attribute_methods/dirty.rb:29:in save!
[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/transactions.rb:273:in block in save!
[GEM_ROOT]/gems/activerecord-4.1.16/lib/active_record/transactions.rb:329:in block in with_transaction_returning_status
```

**Comment by antw** [comment] 2016-09-13 11:40
I have fixed this LES manually. This is a duplicate of #1315 and #1286.

**Closed by antw** 2016-09-13 11:40 UTC
Labels: airbrake
