### ISSUE TITLE
When you go to gas, back to electricity and select other week your stuck

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1033] opened 2016-06-02 12:40 UTC
Loads forever and hangs:

![image](https://cloud.githubusercontent.com/assets/104830/15745035/f9b1ce46-28cf-11e6-8e4d-da59dee9a82c.png)

**Comment by grdw** [comment] 2016-06-02 12:46
Could you try to reproduce this on beta? It sounds as though it's related to #1023

**Comment by ChaelKruip** [comment] 2016-06-02 13:31
Cannot reproduce on LIVE or BETA at the moment...

Closing. Re-open if this re-occurs.

**Closed by ChaelKruip** 2016-06-02 13:31 UTC
Labels: Bug
