### ISSUE TITLE
Splitting up full year load from weekly load

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#256] opened 2015-08-06 15:18 UTC

**Comment by grdw** [comment] 2015-08-10 13:15
![screen shot 2015-08-10 at 3 14 43 pm](https://cloud.githubusercontent.com/assets/2676542/9172250/9cf65326-3f72-11e5-9aa1-4fc9a552c300.png)

How it looks. 

@ChaelKruip please take a look

**Comment by ChaelKruip** [comment] 2015-08-10 15:11
We have decided not to do this in the end. It is not obvious what the expected behaviour should be for downscaling: take the maximum (as currently done), the minimum, the average?
We decided to make two separate charts: the current yearly one and one with full resolution for the weeks. 

Closing.

**Closed by ChaelKruip** 2015-08-10 15:11 UTC

**Comment by antw** [comment] 2015-08-13 15:17
> We have decided not to do this in the end.

Pity; I was quite keen on the idea. :disappointed: 

What's the *goal* of having separate annual and weekly charts visible at the same time? I think the user experience is worse, because it's not clear *why* there needs to be two separate charts, and it adds clutter to the page.

I can imagine end-users asking:

* "Do they display identical data?"
* "Why can I zoom in on a weekly chart but not an annual one?"
* "Why can I have Jan 6th and 7th on a weekly chart (same week) but not the 7th and 8th?"

If we must do this, could we only show one chart at-a-time by using tabs?

```
   +----------------------+-----------------------+
   |  Daily maximum load  |  Instantaneous loads  |
---+                      +-----------------------+------------------------
```

> It is not obvious what the expected behaviour should be for downscaling: take the maximum (as currently done), the minimum, the average?

We don't show the maximum value, we show [the maximum "deviation" from zero](https://github.com/quintel/etmoses/blob/7808bd38f6519e56d5a8315c7bcfbb7e36108000/app/assets/javascripts/testing_grounds.js.coffee#L179) (maximum absolute value?), i.e. if a sample has three values – `[1.0, 4.0, -5.0]` – then `-5` is the one which will be plotted.

I feel like we could workaround this problem somewhat by more information in the tooltips:

![tooltip-summary](https://cloud.githubusercontent.com/assets/4383/9253579/6e694fb6-41d6-11e5-8a35-47421b8d48f9.png)

**Comment by dennisschoenmakers** [comment] 2015-08-14 07:19
Hmmm, maybe we missed an opportunity to discuss options when you where here @antw? Maybe we could go through the options with you once more? What do you think @ChaelKruip ?

**Comment by ChaelKruip** [comment] 2015-08-17 12:51
> maybe we missed an opportunity to discuss options when you where here @antw

Unfortunately it slipped my mind indeed! 

> I can imagine end-users asking: [...]

I am susceptible to your argumentation @antw but I am not convinced (yet?) that any form of down-sampling is actually helping the user to understand the situation. Our (@dennisschoenmakers, @grdw andy myself discussed this a week ago) arguments for separating the yearly chart and the weekly chart were as follows:

* The yearly chart is nice as a quick 'overview' but 'hides' too much information. The user will be confused if no solar production seems to be included in the system (smaller negative values are suppressed because of the current choice of showing the maximum deviation only)
* The user might be confused because he can select individual weeks and yearly demands in the same drop-down menu (this would be solved by proper dynamic scaling)
* The user should be invited to inspect the load at its real resolution

> If we must do this, could we only show one chart at-a-time by using tabs?

:+1: 

> Pity; I was quite keen on the idea.

Perhaps I was a bit too definitive in my comment :worried: 
I would like to have a fancy dynamically scaled resolution chart too but I think it should be able to do the following things:

* Be intuitive
* Have good performance ( @grdw's first attempts were quite 'laggy')
* Show meaningful values when down-sampled data is shown. We would have to think about this more.

I think the Google finance charts check the first two boxes but I have the feeling that making their functionality from scratch is no trifling matter (hence the price tag). A nice-to-have for the future?

**Comment by antw** [comment] 2015-08-17 13:06
> Show meaningful values when down-sampled data is shown. We would have to think about this more.

Two options come to mind: 

1. [An area range](http://www.highcharts.com/demo/arearange-line) which shows the largest positive and negative loads for a period.
2. Better yet: [a candlestick/box chart](http://www.highcharts.com/stock/demo/intraday-candlestick). Here's [another example](http://www.highcharts.com/demo/box-plot).

Not saying this is easy, but it would be nice.

> Have good performance ( @grdw's first attempts were quite 'laggy')

I had the same problem when I was experimenting with this earlier in the project. I'm not sure if it's the browser itself or the NVD3.js library, but I found performance really suffered when the data was highly variable: nice smooth lines seemed to perform quite well even with many data points (1000+), while those which result in very jagged lines performed badly.
