### ISSUE TITLE
Why are capacities defined for electric heatpumps?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1602] opened 2017-02-27 10:22 UTC
In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/958) the technologies tab shows 2 kWh buffersize for the three water heating buffers and 1.5 kWh for space heating. This is correct, I set these values.

I noticed that there is also a storage defined for the **heating technologies** (heat pump air). The size is 81 kWh for Heat pump for hot water (air) and 174 kWh for Heat pump for space heating (air). (This size does not change when I adjust the buffer size of the corresponding buffer)
This is the only technology that has a storage volume defined. 

**Is there a reason for this? I would say storage volume for the technology should be NaN.**
<br>

![image](https://cloud.githubusercontent.com/assets/19907658/23357381/cd10e06a-fcdd-11e6-80f0-d7607c22ce2d.png)

Notifying @AlexanderWirtz 
Assigning @grdw, please reassign if appropriate

**Comment by antw** [comment] 2017-02-27 11:04
> In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/958) the [...]

Is this the correct LES? If so, I think it has been edited since the screenshot and the heat pumps have been replaced with HHPs. Therefore I can't tell if it's a (weird) display issue, or if those volumes are actually being saved with the technology data.

I cloned the LES, added a heat pump and messed around with the attributes for the pump and the parent buffer, but I can't seem to reproduce this. Do you remember editing the LES in some way *before* you noticed this problem?

**Comment by DorinevanderVlies** [comment] 2017-02-27 11:16
I'm sorry, I linked to the wrong LES. [This LES (ID 949)](https://beta-moses.energytransitionmodel.com/testing_grounds/949) has electric heatpumps and shows the storage volume for the heatpumps.

I now notice the values are also shown in the csv in the CSV of this LES.

> Do you remember editing the LES in some way before you noticed this problem?
I did make changes to the LES, I'm not sure which and what cause the error.

Other LESses with heat pump air [like this one](https://beta-moses.energytransitionmodel.com/testing_grounds/956) do not show storage volume for the heatpumps.

I propose that if you can't find what's wrong with LES 949 I close this issue for the time being and reopen when the issue occurs again.

**Comment by antw** [comment] 2017-06-16 09:11
This doesn't appear to be a problem for newly-created LESes; this scenario may be a clone from a one created before we had shared buffers, or the problem has been fixed. The value shown won't have any effect on the calculation of the LES as the shared buffer will be used instead.

If it's annoying, we can remove the values manually from any affected scenario.

I'll close this; please reopen if you find this happens again.

**Closed by antw** 2017-06-16 09:11 UTC
Labels: Bug, Question
