### ISSUE TITLE
Interface to view load profile has non-working buttons

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1149] opened 2016-06-28 14:48 UTC
**Problem**
The interface to view the base load profiles is not working properly.
Two charts (flex and inflex) are shown with two buttons to specify the time interval. Both buttons influence to bottom chart. 
Whether the buttons both affect the top or bottom chart, or work properly, varies for the different profiles

**Examples**
[E1A](https://beta-moses.energytransitionmodel.com/load_profiles/240) In this profile both buttons influence the bottom chart.

![image](https://cloud.githubusercontent.com/assets/19907658/16419743/1fdb32fe-3d4f-11e6-978c-18f5173a4d81.png)

[E1B](https://beta-moses.energytransitionmodel.com/load_profiles/241) In this profile both buttons influence the top chart.

@dennisschoenmakers

**Comment by ChaelKruip** [comment] 2016-06-28 14:59
Duplicate of https://github.com/quintel/etmoses/issues/326. Closing.

**Closed by ChaelKruip** 2016-06-28 14:59 UTC
Labels: Layout
