### ISSUE TITLE
When changing a technology in 'profile table' set defaults

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#171] opened 2015-06-16 15:18 UTC
For instance:
- capacity
- storage volume
- etc.

**Comment by grdw** [comment] 2015-06-17 09:36
I'm currently extracting the defaults from the first similair row in the table (for instance, if I change the technology to electric car - it will try to see if another electric car is already in the table and fills the 'defaults' with these values). This does mean that for some technologies the defaults will be blank (it just clears the table cells). 

@ChaelKruip  A question that pops up though: should there be defaults for each technology?

**Comment by ChaelKruip** [comment] 2015-06-18 07:51
> I'm currently extracting the defaults from the first similair row in the table

I think it would be better to use the first profile (of allowed type) in the 'profile database' as the default. 

In your current implementation and the example you describe, the user may change the profile of the first EV in the table. If the user than changes another technology to EV, the 'default' profile assigned to it will be the 'changed one'. This is not very deterministic or reproducible IMO. 

> should there be defaults for each technology

For batteries, P2H and P2G there are no profiles. This is by design.

**Comment by grdw** [comment] 2015-06-23 08:23
> I think it would be better to use the first profile (of allowed type) in the 'profile database' as the default. 

That's already happening. It has more to do with the defaults for capacity , storage and demand

**Closed** 2015-06-26 15:24 UTC
Labels: Bug
