### ISSUE TITLE
few seconds waiting for dropdownmenu in technology tale

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#632] opened 2015-11-27 11:40 UTC
If i click on a dropdownmenu of f.e. name in the technology table it takes ET-Moses a few seconds (2-4) to show the dropdownlist.

**Comment by grdw** [comment] 2015-11-27 12:58
Could you copy/paste a link to a LES where this happens?

**Comment by dennisschoenmakers** [comment] 2015-11-27 16:36
Could this be particular to IE?

Sent from my iPhone

On 27 nov. 2015, at 13:58, Gerard Westerhof <notifications@github.com>
wrote:

Could you copy/paste a link to a LES where this happens?

—
Reply to this email directly or view it on GitHub
<https://github.com/quintel/etmoses/issues/632#issuecomment-160134261>.

**Comment by JeroenvdLogt** [comment] 2015-11-27 19:24
i am using google chrome

**Comment by dennisschoenmakers** [comment] 2015-11-27 19:27
> i am using google chrome

Wise decision! :smile: Thanks for telling, then we know it cannot be a cross browser thing.

**Comment by JeroenvdLogt** [comment] 2015-11-27 19:35
http://beta.moses.et-model.com/testing_grounds/376/edit

hereby a link of a les where I encounter the problem

**Comment by dennisschoenmakers** [comment] 2015-11-27 20:21
Here it works very snappy on Chrome... @grdw can you reproduce?

On Fri, Nov 27, 2015 at 8:35 PM, Jeroen van de Logt <
notifications@github.com> wrote:

> http://beta.moses.et-model.com/testing_grounds/376/edit
>
> hereby a link of a les where I encounter the problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quintel/etmoses/issues/632#issuecomment-160194267>.
>



-- 

Dennis Schoenmakers, *Partner*


*Quintel Intelligence*Atrium - Strawinskylaan 3051
1077 ZX  Amsterdam
The Netherlands

*Visiting Address:*
Keizersgracht 639
1017 DT Amsterdam

T  : +31 (0)20 301 22 69
F  : +31 (0)20 301 22 02
M : +31 (0)6 109 65 293

E : dennis.schoenmakers@quintel.com
I  : www.quintel.com and www.energytransitionmodel.com

*This message (including any attachments) is confidential and may be
privileged. Any review, retransmission, dissemination or other use of, or
taking any action with reference to this information by persons other than
the intended recipient is strictly prohibited. If you have received it by
mistake please notify the sender by return e-mail and delete this message
from your system. Please note that e-mails are susceptible to change. The
sender will not accept liability for the improper or incomplete
transmission of the information contained in this message.*

**Comment by antw** [comment] 2015-11-27 20:39
Very slow for me. The page loads with all the technology fields filled in *except* for "Profile" (all those select boxes are blank). But the page then "hangs" for several seconds – with the "Profile" fields still empty – before it then fills in those values.

![screen shot 2015-11-27 at 20 36 58](https://cloud.githubusercontent.com/assets/4383/11447937/a237f180-9546-11e5-9589-e08fadc5a684.png)

Chrome reports that 2.8 seconds is spent running `querySelectorAll` (finding DOM elements by a CSS class):

![screen shot 2015-11-27 at 20 38 13](https://cloud.githubusercontent.com/assets/4383/11447951/dddb1a6e-9546-11e5-9387-18fae06f814c.png)

**Comment by dennisschoenmakers** [comment] 2015-11-29 13:39
I reproduced it as well now. I was looking at the wrong place before.

**Comment by grdw** [comment] 2015-11-30 09:01
I've the same problem in Firefox.

![screen shot 2015-11-30 at 10 00 23 am](https://cloud.githubusercontent.com/assets/2676542/11467552/33228512-9749-11e5-9f80-c004d3b8d2f9.png)

It hangs a couple of seconds than it continues on.

**Comment by dennisschoenmakers** [comment] 2015-11-30 09:09
Probably a jQuery selector is responsible. Can you sort out which one that is @grdw ?

**Comment by grdw** [comment] 2015-11-30 09:51
https://github.com/quintel/etmoses/pull/634/files

It had to do with the header. It's basically a selector in a selector which is rather slow.

**Comment by grdw** [comment] 2015-11-30 12:23
This all has to do with the old interface so I'm not sticking too much time into it.

The new interface was also a little sluggish but less so as the old one.
There was one culprit though that made it a little slower.

![screen shot 2015-11-30 at 11 34 05 am](https://cloud.githubusercontent.com/assets/2676542/11469391/4d648a26-9756-11e5-910c-4fce9c64cb12.png)

I replaced it with a simple javascript regex solution.

**Comment by dennisschoenmakers** [comment] 2015-11-30 12:48
> This all has to do with the old interface so I'm not sticking too much time into it.

In that case: closing this issue. Let's focus on the new interface.

**Closed by dennisschoenmakers** 2015-11-30 12:48 UTC
Labels: Bug, Minor issue
