### ISSUE TITLE
Cashflow model

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1205] opened 2016-07-06 09:16 UTC
Besides the total business case it would be nice if the cashflows between the different stakeholders could be displayed. This would provide more information than the business case.

**Comment by ChaelKruip** [comment] 2016-07-06 09:19
How is this different from the business case matrix?
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16613260/85ca1b3a-436b-11e6-9ac2-889de2bd71c8.png)

**Comment by ChaelKruip** [comment] 2016-07-06 09:20
Also see https://github.com/quintel/etmoses/issues/1090

**Comment by ChaelKruip** [comment] 2016-07-10 17:20
Closing because duplicate of #1090

**Comment by Sanne512** [comment] 2016-07-30 17:23
> How is this different from the business case matrix?

It would be different, because it would be nice to see the seperate cash flows and not only the total cash flow from one stakeholder to another and it would be nice to see which technologies make up the deprecation costs. What do you think about this idea @ChaelKruip ?

Including @MarjoleinSchwachofer

**Comment by ChaelKruip** [comment] 2016-08-02 07:57
> It would be different, because it would be nice to see the seperate cash flows and not only the total cash flow from one stakeholder to another and it would be nice to see which technologies make up the deprecation costs. What do you think about this idea @ChaelKruip ?

Great idea! It was already described in #1090 though 😜 . Closing therefore.

**Closed by ChaelKruip** 2016-08-02 07:57 UTC
Labels: Enhancement
