### ISSUE TITLE
[Airbrake] [Production] Validation failed: Technology profile includes a connection to missing node "Eengezin 55a", Technology profile includes a connection to missing node "Eengezin 35a", Technology profile includes a connection to missing node "Eenge...

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1412] opened 2016-09-06 06:44 UTC
**Airbrake error:** [#4956](https://quintel.airbrake.io/projects/111227/groups/1768656416306344956)
**Airbrake project:** ETMoses

**Error type:** `ActiveRecord::RecordInvalid`
**Error message:** `` Validation failed: Technology profile includes a connection to missing node "Eengezin 55a", Technology profile includes a connection to missing node "Eengezin 35a", Technology profile includes a connection to missing node "Eengezin 45a", Technology profile includes a connection to missing node "Eengezin 36a", Technology profile includes a connection to missing node "Eengezin 8b", Technology profile includes a connection to missing node "Eengezin 35b", Technology profile includes a connection to  ``
**Where:** `testing_grounds#save_as`
**Occurred at:** Sep 06, 2016 06:44:34 UTC
**First seen at:** Sep 06, 2016 06:44:34 UTC
**Occurrences:** 1 (1 since last deploy on Jul 18, 2016 11:54:39 UTC)

**URL:** [https://moses.energytransitionmodel.com/testing_grounds/518/save_as](https://moses.energytransitionmodel.com/testing_grounds/518/save_as)
**File:** `[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/validations.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in block in save!
[GEM_ROOT]/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in block in with_transaction_returning_status
```

**Comment by grdw** [comment] 2016-09-06 14:20
Duplicate of #1399

**Closed** 2016-10-15 12:59 UTC
Labels: airbrake
