### ISSUE TITLE
Units and capacities work differently on pro en beta server, pro does not work like said in the documentation

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1340] opened 2016-07-27 14:35 UTC
The capacities and units multiplication do not work correctly everywhere. They work differently on the pro and beta server.

In the LES test 2 on the beta server, the capacites and the untis are multiplied, just as it states how it works in the documentation. 
![image](https://cloud.githubusercontent.com/assets/17849585/17178892/7abf8984-5417-11e6-9e33-1b4fd4a53337.png)
![image](https://cloud.githubusercontent.com/assets/17849585/17178912/8e98b5ca-5417-11e6-89ac-d05b752f4671.png)

However on the pro server, LES  Lunch and Learn - Buurtbatterij, the capacities and units are not multiplied (at least the red congestion line is not). Capacity huishoudens is 3400, while the topology file give capacity: 3400,  units: 200 so the capacity should be 680000 (she coreect it manuaaly because the multiplication doesn't work)

![image](https://cloud.githubusercontent.com/assets/17849585/17178775/0b58ca2e-5417-11e6-9772-8e3ce1065de9.png)
![image](https://cloud.githubusercontent.com/assets/17849585/17178855/582475b0-5417-11e6-9fed-810efb20b35d.png)

Attention when fixing this  on the pro server is needed, because in old LES'es that use a topology in which the fault is manually corrected (like the buurtbatterij, which is used for analysis within Alliander), wilt give wrong results of overloading when the working of units and capacities is adapted.

**Comment by MarjoleinSchwachofer** [comment] 2016-07-28 09:47
Related question, why is in the above mentioned LES test 2 on the beta server, the node in topology red, while in the graph no overloading is shown:
![knipsel](https://cloud.githubusercontent.com/assets/17849585/17208434/04a33dd4-54b9-11e6-9df8-ea5585e5fdf7.JPG)

**Comment by antw** [comment] 2016-07-28 13:14
This is a duplicate of #1095 and has been fixed on beta. Changes (fixes and new features) are published immediately to the "beta" server. The "pro" server will be updated once we are confident that the heat network feature is stable and reliable.

The capacity *is* correctly scaled by the number of `units` during the network calculation on the "pro", it is just – unfortunately – drawn on the wrong place on the chart.

**Closed by antw** 2016-07-28 13:14 UTC
Labels: Bug
