### ISSUE TITLE
[Airbrake] [Staging] undefined method `attributes' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1334] opened 2016-07-27 10:32 UTC
**Airbrake error:** [#1172](https://quintel.airbrake.io/projects/111227/groups/1739055182935211172)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `attributes' for nil:NilClass ``
**Where:** `gas_asset_lists#update`
**Occurred at:** Jul 27, 2016 10:32:12 UTC
**First seen at:** Jul 27, 2016 10:32:12 UTC
**Occurrences:** 1 (1 since last deploy on Jul 25, 2016 16:43:32 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/663/gas_asset_lists/671](https://beta-moses.energytransitionmodel.com/testing_grounds/663/gas_asset_lists/671)
**File:** `[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:21:in block in decorate
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:18:in map
[PROJECT_ROOT]/app/models/gas_asset_list_decorator.rb:18:in decorate
[PROJECT_ROOT]/app/controllers/gas_asset_lists_controller.rb:11:in update
```

**Comment by antw** [comment] 2016-07-28 14:29
Duplicate of #1335 and closed by 061f66a4.

**Closed by antw** 2016-07-28 14:29 UTC
Labels: airbrake
