### ISSUE TITLE
Buffering/boosting should be shown when importing from CSV

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1158] opened 2016-07-04 11:37 UTC
The values are set by the import action but not shown in the front-end.

**Comment by grdw** [comment] 2016-07-05 11:47
I'm having a bit of hard time reproducing this locally.

What I do, fetch a CSV, import a scenario (scenario id on beta = 515515). Than I remove all technologies from the profile. Select a CSV and hit "Create Local energy solution". 

![screen shot 2016-07-05 at 13 46 18](https://cloud.githubusercontent.com/assets/2676542/16583592/df06cc62-42b6-11e6-888b-beffd90e42d3.png)

I think @antw might have fixed this :)

**Comment by ChaelKruip** [comment] 2016-07-06 10:28
> I think @antw might have fixed this :)

Is this the case @antw?

**Comment by antw** [comment] 2016-07-06 10:45
> I think @antw might have fixed this :)

If I have, it wasn't intentional. 😆

**Comment by ChaelKruip** [comment] 2016-07-14 10:07
@grdw is this still an issue? If so, what is the status?

**Comment by grdw** [comment] 2016-08-23 13:04
<img width="1061" alt="screen shot 2016-08-23 at 15 03 00" src="https://cloud.githubusercontent.com/assets/2676542/17892649/b7212b36-6942-11e6-9c10-be485180d1a6.png">

This is what I now see happening. Is this what you mean or is this something else?

**Comment by ChaelKruip** [comment] 2016-08-23 14:16
> This is what I now see happening. Is this what you mean or is this something else?

This seems to be fine. When @DorinevanderVlies was importing the technologies through CSV, the two radio buttons where both not selected for many technologies. If this no longer happens we can close this. 

Did you try initialising the technology matrix with CSVs @grdw?

**Comment by grdw** [comment] 2016-08-24 07:12
> Did you try initialising the technology matrix with CSVs @grdw?

Yes, I did the hacky version of ['forgetting the name'](https://github.com/quintel/etmoses/issues/1157#issuecomment-241718608). Maybe that's what is causing this bug in the first place. I need to test again . Moment please.

**Comment by grdw** [comment] 2016-08-24 07:18
I can't seem to reproduce this issue. Therefor closing. I'm assuming this is caused by a typo in the csv? Otherwise you can always re-export the CSV to make sure that all the headers are correct.

**Closed by grdw** 2016-08-24 07:18 UTC
Labels: Bug
