### ISSUE TITLE
EV buffering only when network has spare room strategy not fully functional

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1452] opened 2016-09-22 07:31 UTC
I think that in [my LES](https://moses.energytransitionmodel.com/testing_grounds/596) the calculator does not take some load (heat pumps?) into account when calculating how much the EV should consume to alleviate the congestion of the network:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/18739925/2cdd3718-80a7-11e6-9063-a6bb63116c1a.png)
The stacked load chart:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/18739951/4fe3a58a-80a7-11e6-9be2-81e1d8292b0f.png)

**Comment by antw** [comment] 2016-09-22 09:59
Closing as a duplicate of #1453. See: https://github.com/quintel/etmoses/issues/1453#issuecomment-248859383.

**Closed by antw** 2016-09-22 09:59 UTC
Labels: Bug, Priority
