### ISSUE TITLE
BUG: Gas load chart shows up when I was expecting the electricity load

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1027] opened 2016-06-02 12:10 UTC
![image](https://cloud.githubusercontent.com/assets/104830/15744348/af50955c-28cb-11e6-8763-792aafa52916.png)

It is also inconsistent with the **date selector** 😭 

To reproduce:

1. load https://moses.energytransitionmodel.com/testing_grounds/476

**Comment by grdw** [comment] 2016-06-02 12:54
![screen shot 2016-06-02 at 14 54 20](https://cloud.githubusercontent.com/assets/2676542/15745391/e8aeecee-28d1-11e6-983e-50c3a698b9c6.png)

I'm currently getting an error.

**Comment by grdw** [comment] 2016-06-02 12:58
Removed the cache (because there was one file missing?) and reloaded the page and I have the current load again. Also with just this one single step I'm not able to reproduce this. Is there anything else that you did to achieve this? Switch tabs really fast etc. anything?

**Comment by ChaelKruip** [comment] 2016-06-02 13:06
The main issue is why it regularly happens that some caching-related problem makes a LES 'hang'. 

I cannot reproduce this now. 
Closing.

**Closed by ChaelKruip** 2016-06-02 13:06 UTC
Labels: Bug
