### ISSUE TITLE
Yearly gas flow chart/graph isn't loading

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1328] opened 2016-07-26 14:18 UTC
On the pro as wel as beta server the yearly gas flow chart isn't loading. 

I wanted to check how this looked when there is gas feed in by P2G; to see if this is working.
I coulsn't do this because  the chart doesn't load. I get the following message:
Sorry, the chart could not be loaded.

**Comment by ChaelKruip** [comment] 2016-07-26 15:18
Closing as this is a duplicate of https://github.com/quintel/etmoses/issues/1050 which is being worked on in the current sprint.

**Closed by ChaelKruip** 2016-07-26 15:18 UTC
Labels: Bug
