### ISSUE TITLE
Solar capping doesn't work

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1271] opened 2016-07-14 13:02 UTC
In the LES Lunch and Learn - Buurtbatterij https://moses.energytransitionmodel.com/testing_grounds/512 solar capping doesn't work. I selected solar capping and put the slider on 100%, but as you can see in the picture below it eliminates the load on the demand side and not on the supply side as it should.

![bug solar capping 20160714](https://cloud.githubusercontent.com/assets/17741822/16840220/cf61cdba-49d3-11e6-8b12-13208bf5e4da.PNG)

**Comment by ChaelKruip** [comment] 2016-07-14 13:46
Assigning @antw

**Comment by antw** [comment] 2016-07-14 13:51
Here's the weekly load for 3rd July.

| Capping off | Capping on; 100% |
| --- | --- |
| <img width="571" alt="screen shot 2016-07-14 at 14 49 58" src="https://cloud.githubusercontent.com/assets/4383/16841698/5412b13e-49d2-11e6-93b5-f574fca00107.png"> | <img width="589" alt="screen shot 2016-07-14 at 14 49 47" src="https://cloud.githubusercontent.com/assets/4383/16841701/5752de96-49d2-11e6-8e0b-e5f21a302e0c.png"> |

Capping appears to be working fine. I suspect this is a duplicate of #1254 which I shall look into now.

**Closed by antw** 2016-07-14 13:51 UTC
Labels: Bug
