### ISSUE TITLE
Gas load graphs do not load

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#980] opened 2016-05-19 12:34 UTC
When I try to view the impact on the gas load by clicking the gas load tab I get an error and it doesn't show  the graphs. This happens in the following LES: 

https://beta-moses.energytransitionmodel.com/testing_grounds/504

**Comment by antw** [comment] 2016-05-19 12:40
Seems to be caused by #976. I'll close this duplicate issue and take a look into it.

**Closed by antw** 2016-05-19 12:40 UTC
Labels: Bug

**Comment by antw** [comment] 2016-05-19 12:57
@Sanne512 I have fixed the problem in that testing ground, but I'm not sure how the error was caused in the first place. If this happens again, can you let us know and – if possible – try to recall the actions you took before the error occurred? Thanks!
