### ISSUE TITLE
Wanted: download load curve for a whole year with quarterly values

### ISSUE THREAD

**Issue by Stefan-87** [quintel/etmoses#1361] opened 2016-08-10 07:30 UTC
In the beta version of ETMoses, it is possible to download the results of your LES, including the strategies, as load curves (.CSV file). When downloading the results of a week you get quarterly values (672 entries), however, if you download the file for a whole year, you get daily values (365 entries). Would it be possible to generate these output files for a whole year with quarterly values, so a more detailed analyses can be done?

And when will the download feature be available in the regular version of ETMoses?

**Comment by ChaelKruip** [comment] 2016-08-10 07:41
@Stefan-87 Thank you for participating actively on Github! A few pointers:

* Select one or more labels to indicate what type of ticket this is
* Assign someone (when in doubt, assign me) so your ticket gets looked at
* In the future, please search for similar issues than the one you are experiencing so you don't have to create a new issue each time you encounter an error or have a question. Let me know if you need help with the search functionality!

Closing as this is a duplicate of https://github.com/quintel/etmoses/issues/1296.

**Closed by ChaelKruip** 2016-08-10 07:41 UTC
Labels: Enhancement
