### ISSUE TITLE
I would prefer not to 'guess' what happened with the strategies selected

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#362] opened 2015-09-10 07:33 UTC
But I need a bit more information.

E.g.:

![image](https://cloud.githubusercontent.com/assets/104830/9782575/8dc12680-579e-11e5-8b09-463aeacd900d.png)

Especially if you select multiple strategies, you'll have  to understand what is going on. E.g. in the picture above, the load could as well have been capped... :scream: 

### Possible solution
I think it would be very helpful if we can add series to the chart that depicts the load that goes into a certain technology (e.g. ev, or home batteries)

**Comment by dennisschoenmakers** [comment] 2015-09-10 07:33
cc @ChaelKruip

**Comment by antw** [comment] 2015-09-14 15:56
> I think it would be very helpful if we can add series to the chart that depicts the load that goes into a certain technology (e.g. ev, or home batteries)

I'm tempted to close this as a duplicate of #74. @dennisschoenmakers Does that issue adequately describe your solution?

We also previously discussed adding a chart to show how much is being stored in batteries, heat pump tanks, etc. That might go a long way to explaining changes between the blue and green lines.

**Comment by dennisschoenmakers** [comment] 2015-09-15 07:17
> I'm tempted to close this as a duplicate of #74. @dennisschoenmakers Does that issue adequately describe your solution?

Yes!

> We also previously discussed adding a chart to show how much is being stored in batteries, heat pump tanks, etc. That might go a long way to explaining changes between the blue and green lines.

That would absolutely also add to understand what is going on. For instance: you could easily tell that your buffers are full, and hence you cannot dump excess local production anymore, et cetera.

**Closed** 2016-06-30 13:28 UTC
