### ISSUE TITLE
LIVE crashes when selecting a week after calculating whole year

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1060] opened 2016-06-10 08:32 UTC
In [this LES](https://moses.energytransitionmodel.com/testing_grounds/481), I just calculated the whole year which displayed fine. After showing the capacity line in the load chart I selected the first week of the year. Now it is stuck...

**Comment by antw** [comment] 2016-06-10 09:42
Duplicate of #1028. Fixed it by removing the cache for this LES. I still don't know what really causes this – except that it's related to the cache somehow – but I'll investigate it later today once heat buffering is completed.

**Closed by antw** 2016-06-10 09:42 UTC
Labels: Bug, Priority
