### ISSUE TITLE
The marginal costs [EUR/kWh] for the heat sources are not shown in the business case

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1593] opened 2017-01-18 08:40 UTC
### Summary
The marginal costs [EUR/kWh] for the heat sources are not shown in the business case.

### Detail
The real reason behind this issue is that I want to know the split between the supply of the two heat sources.
To calculate this I made a [simplified LES](https://beta-moses.energytransitionmodel.com/testing_grounds/904/edit). It contains just the heat demand, sources and assets.

The heat source list defines marginal costs of 1 EUR/kWh to Customer Ac3 and Ac4 for respectively the Geothermal and the Biogas CHP source. So, Euro/year of Customer Ac3 should show # of kWh produced by the geothermal source. Euro/year of Customer Ac4 should show # of kWh produced by the geothermal source.

The market model defines 1 euro / kWh of heat from stakeholder 1 to stakeholder 1a. This is a check. The income of customer 1a should equal the total out of Customer Ac3 and Ac4.

**However, outgoing of stakeholder Customer Ac3 and Customer Ac4 are both 0.**

### Images
![image](https://cloud.githubusercontent.com/assets/19907658/22056534/d9f2d23a-dd60-11e6-97ce-d208b282a45d.png)

![image](https://cloud.githubusercontent.com/assets/19907658/22056769/093ef892-dd62-11e6-931f-b7cd1236b018.png)

**Comment by ChaelKruip** [comment] 2017-01-18 08:52
> The marginal costs [EUR/kWh] for the heat sources are not shown in the business case.

This is not a bug but a feature! Because marginal costs for heat are very uncertain, the numbers provided here are indicative only. If the user wants to include them as costs for the stakeholders, that should be modelled in the explicitly in the market model.

**Comment by DorinevanderVlies** [comment] 2017-01-18 08:58
> The real reason behind this issue is that I want to know the split between the supply of the two heat sources

I found another workaround. The geothermal source is both the first source and the bottleneck. I made a second simplified LES with just the geothermal source. This results in deficits which in the other LES are filled with the CHP source.

The difference between heat production in both LES's is the heat produced by the CHP source.

**Comment by ChaelKruip** [comment] 2017-01-18 10:09
@DorinevanderVlies shall we close this issue and can you make a new one with the feature request for a way to assess the total production of heat sources?

**Comment by DorinevanderVlies** [comment] 2017-01-18 10:17
> @DorinevanderVlies shall we close this issue and can you make a new one with the feature request for a way to assess the total production of heat sources?

I think we need two issues. One about the marginal costs and one about the production of the heat sources.

Regarding the marginal costs, this issue.
Right now the heat source list contains the cell "Marginal costs [EUR/kWh]". This implies that this cell will be represented in the business case. It currently isn't. So, as long as that input cell is present I think this issue is still relevant.

**Comment by ChaelKruip** [comment] 2017-01-18 10:32
> This implies that this cell will be represented in the business case.

It may suggest that it does (as the other fields are taken into account). How could we clarify that it is not?

I'm not sure if I'm in favour of adding it automatically to the BC (because of the uncertainties involved). At the same time, gas consumption of combi-boilers (part of the marginal costs) needs to be explicitly added to the market model as well...

>It currently isn't. 

In the [documentation](https://github.com/quintel/etmoses/wiki/Heat-network) this is mentioned:

Marginal costs [EUR/kWh]: the costs of producing one kWh of heat (including fuel costs, variable O&M costs and, possibly, costs for emitting CO2). NOTE: Marginal costs are not taken into account in the business case automatically. Of course, the user can manually use these marginal costs as fixed tariffs for heat production in Market models.

**Comment by DorinevanderVlies** [comment] 2017-01-18 13:16
> In the documentation this is mentioned:

True point. I missed this completely... I can imagine more people will not read the documentation thoroughly.

> I'm not sure if I'm in favour of adding it automatically to the BC (because of the uncertainties involved).

Another option might be to set the default value to 0 and leave it to the user to decide whether it wants to include these marginal costs and what value to give them.

---

I'm not a huge fan of the current marginal costs input field which is not used in calculations. I would either remove it, or use it in the business case calculation (with default 0 euro/kWh)

Right now it is difficult for a user to implement this calculation themselves. For this issue #1594 needs to be addressed first.

**Comment by ChaelKruip** [comment] 2017-01-20 08:41
> Another option might be to set the default value to 0 and leave it to the user to decide whether it wants to include these marginal costs and what value to give them.

I like this! It is easy to implement and perhaps more intuitive as well.

**Comment by DorinevanderVlies** [comment] 2017-02-03 09:31
Including @AlexanderWirtz

**Comment by antw** [comment] 2017-02-06 12:34
> > Another option might be to set the default value to 0 and leave it to the user to decide whether it wants to include these marginal costs and what value to give them.
>
> I like this! It is easy to implement and perhaps more intuitive as well.

I can set the default marginal costs to zero, but we cannot (easily) use the marginal costs of heat sources. The marginal cost is a measure of price per kWh of heat produced; the way you would do this in the current system is to add an interaction in the market model. In order to set a different price for each heat source you would have to assign each one to a unique stakeholder; far from ideal.

We *can* adapt the market model system to support the desired behaviour, but I think it will take too long to do this before Wednesday's scheduled deploy, unless this is very important.

The most intuitive short-term solution might be to remove the marginal cost field; I agree with @DorinevanderVlies that it is confusing for it to be shown but not included in the business case.

**Comment by ChaelKruip** [comment] 2017-02-06 13:25
> The most intuitive short-term solution might be to remove the marginal cost field;

Fine by me!

**Closed** 2017-02-06 16:25 UTC
Labels: Enhancement
