### ISSUE TITLE
[Airbrake] [Staging] key not found: "buffer_space_heating_1"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#977] opened 2016-05-19 08:40 UTC
**Airbrake error:** [#4499](https://quintel.airbrake.io/projects/111227/groups/1688989892382014499)
**Airbrake project:** ETMoses

**Error type:** `KeyError`
**Error message:** `` key not found: "buffer_space_heating_1" ``
**Where:** `gas_asset_lists#load_summary`
**Occurred at:** May 19, 2016 08:40:33 UTC
**First seen at:** May 19, 2016 08:40:33 UTC
**Occurrences:** 1 (1 since last deploy on May 18, 2016 15:38:56 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/389/gas_asset_lists/111/load_summary](https://beta-moses.energytransitionmodel.com/testing_grounds/389/gas_asset_lists/111/load_summary)
**File:** `[PROJECT_ROOT]/app/models/calculation/technology_load.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:88:in fetch
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:88:in composite
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:48:in block (2 levels) in techs_for
[PROJECT_ROOT]/app/models/installed_technology/profile_curve.rb:17:in block in each
```

**Comment by grdw** [comment] 2016-05-25 09:30
Possible duplicate of:  #892

**Closed** 2016-05-25 09:32 UTC
Labels: airbrake
