### ISSUE TITLE
Cannot load gas load charts and heat load

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1165] opened 2016-07-05 09:28 UTC
When I try to display the gas load charts I get the message "sorry the chart could not be loaded".
![gas load](https://cloud.githubusercontent.com/assets/20039533/16581039/c26d44aa-42a7-11e6-94bc-d365dbe31467.png)
For the heat load I get the following chart:
![heat load](https://cloud.githubusercontent.com/assets/20039533/16581080/ec8586e4-42a7-11e6-83cb-ef7904e090ba.png)
The LES I am using is: https://beta-moses.energytransitionmodel.com/testing_grounds/574/heat_load

I start from ETM and then I scale it down to 100 residents. Then I create the LES and go to the gas load tab and heat load tab.

**Comment by ChaelKruip** [comment] 2016-07-05 09:39
Closing this as it is a duplicate of https://github.com/quintel/etmoses/issues/1050

**Comment by grdw** [comment] 2016-07-05 10:13
The heat load is an Internet Explorer 11 specific issue. I'll look into it and fix it asap.

**Closed** 2016-07-05 10:32 UTC
Labels: Bug
