### ISSUE TITLE
[Airbrake] [Staging] undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1291] opened 2016-07-18 13:50 UTC
**Airbrake error:** [#4193](https://quintel.airbrake.io/projects/111227/groups/1732632894513854193)
**Airbrake project:** ETMoses

**Error type:** `NoMethodError`
**Error message:** `` undefined method `*' for nil:NilClass ``
**Where:** `testing_grounds#data`
**Occurred at:** Jul 18, 2016 13:49:41 UTC
**First seen at:** Jul 18, 2016 13:49:41 UTC
**Occurrences:** 1 (1 since last deploy on Jul 18, 2016 12:54:48 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/578/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/578/data.json)
**File:** `[PROJECT_ROOT]/app/models/calculation/technology_load.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:81:in block in comps_for
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in each_with_object
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:77:in comps_for
```

**Comment by antw** [comment] 2016-07-18 13:58
Duplicate of #1138. Fixed the LES manually for now.

**Comment by dennisschoenmakers** [comment] 2016-07-18 14:01
*Comment from Airbrake:* Resolved [error](https://quintel.airbrake.io/projects/111227/groups/1732632894513854193) reoccurred.

**Comment by antw** [comment] 2016-07-18 14:02
No Airbrake! Bad Airbrake!

*grumble*

**Closed by antw** 2016-07-18 14:02 UTC
Labels: airbrake
