### ISSUE TITLE
Automatic reset of PV capacity

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#428] opened 2015-09-22 10:42 UTC
In this LES: http://beta.moses.et-model.com/testing_grounds/277/edit

the installed capacity of PV at node "household 3" keeps being reset to -1.5 after other changes of this value and other values in technology table.

**Comment by ChaelKruip** [comment] 2015-09-22 10:54
Assigned @grdw

**Comment by grdw** [comment] 2015-09-22 11:48
![screen shot 2015-09-22 at 1 39 25 pm](https://cloud.githubusercontent.com/assets/2676542/10017519/5e8e8e26-612f-11e5-990d-a5d22e9b1cab.png)

How would I reproduce this?
I do see that if I'd take these steps:

1) I made a LES one solar panel to a single household with the default topology
2) Changed the capacity to -2.0 instead of -1.5
3) Saved it
4) Edited the LES
5) Changed the solar panel capacity to -200.0
3) Added a new solar panel

I see that - for the new solar panel - the capacity automatically becomes -2.0 instead of -1.5. Which might not be the intendend behavior. Still I'm not sure if that's exactly the same problem you're describing.

**Comment by JeroenvdLogt** [comment] 2015-09-22 14:44
1. I made the LES from ETM scenario 414971 with default topology and market model test
2. Saved the LES 
3. Viewed the load profile on different nodes
4. Edited LES by chaning Pv capacity of household 3 to -5.0
5. Saved the LES
6. Viewed the load profile on different nodes
7. Edit LES and saw that PV capacity of house household 3 was reset to -1.5

**Comment by JeroenvdLogt** [comment] 2015-09-22 14:48
This is strange, after I wrote previous comment I am not able to reproduce the error. It seems the problem is solved or that I did something wrong or the error was temporarily.

**Comment by grdw** [comment] 2015-09-25 09:11
I'm closing this issue due to the fact that it's hard to reproduce. If it occurs again you can re-open this issue.

**Closed by grdw** 2015-09-25 09:11 UTC
Labels: Bug
