### ISSUE TITLE
BUG: Business case is not calculated at all

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#739] opened 2016-02-04 15:20 UTC
![image](https://cloud.githubusercontent.com/assets/104830/12819359/0a8ebf44-cb5b-11e5-9bd8-2ddf250d3527.png)

As reported by @JeroenvdLogt 

LES: http://beta.moses.et-model.com/testing_grounds/412

**Comment by JeroenvdLogt** [comment] 2016-02-04 15:25
Same problem on production server :(

**Comment by grdw** [comment] 2016-02-04 15:27
> LES: http://beta.moses.et-model.com/testing_grounds/412

I put the business case - for the relevant LES - back in the cue and it calculated. 

![screen shot 2016-02-04 at 4 27 20 pm](https://cloud.githubusercontent.com/assets/2676542/12819646/2f5c1492-cb5c-11e5-9d69-9aa68e184503.png)

**Comment by JeroenvdLogt** [comment] 2016-02-04 15:28
I see that the problem is solved. Thank you for the quick reaction.

**Comment by grdw** [comment] 2016-02-04 15:28
> Same problem on production server

I'll try to see what this problem is. I think it's the same as last time but I'll check to be sure.

**Comment by antw** [comment] 2016-02-04 15:35
> I'll try to see what this problem is.

I think this was an ETEngine issue. With some luck, [now fixed](https://github.com/quintel/etengine/commit/fb56e041ba31ac83b78feb59daa7cf779ad5cf87).

**Closed** 2016-02-04 16:30 UTC
Labels: Bug, Priority
