### ISSUE TITLE
Gas load of my LES cannot be loaded

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1190] opened 2016-07-05 15:29 UTC
In my [current LES](https://beta-moses.energytransitionmodel.com/testing_grounds/572/gas_load
) I get the error that my gas load chart cannot be loaded. 

I have not made any changes to the gas infrastructure. The basic infrastructure should work right?

![image](https://cloud.githubusercontent.com/assets/19907658/16589976/e222a050-42d5-11e6-944c-2f4b58591261.png)

@dennisschoenmakers FYI

**Comment by ChaelKruip** [comment] 2016-07-06 07:38
Closing as this is a duplicate of https://github.com/quintel/etmoses/issues/1050

**Closed by ChaelKruip** 2016-07-06 07:38 UTC
Labels: Bug, Question
