### ISSUE TITLE
P2H strategy does not conform to expectation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#298] opened 2015-08-24 14:03 UTC
This is the observed behaviour with only solar panels and P2H devices: 
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9441004/cb5b3036-4a73-11e5-807e-d29d2d55a8f5.png)
I would expect the P2H device to use excess PV electricity as long as its tank is not full (which doesn't seem to happen). The tank should be emptied using a hot water demand profile (see https://github.com/quintel/etmoses/issues/296). This does not result in any load, however. The extra load (in between the solar PV peaks) is therefore not expected.

**Comment by antw** [comment] 2015-08-27 08:47
Modelling or calculation issue, so I'll reassign this to me.

**Comment by antw** [comment] 2015-09-16 14:55
I made a small fix, but I couldn't reproduce the situation with the positive load documented in the original post. It might have been profile-related, but more likely it was fixed by the recent heat pump changes; `OptionalBuffer` (P2H) is a subclass of `Buffer` (heat pumps).

See LES: **[P2H+PV](http://beta.moses.et-model.com/testing_grounds/271)**.

![screen shot 2015-09-16 at 15 52 36](https://cloud.githubusercontent.com/assets/4383/9908305/fc76c74c-5c8a-11e5-88c7-0a5e6a7837e6.png)

![screen shot 2015-09-16 at 15 52 28](https://cloud.githubusercontent.com/assets/4383/9908309/ffbda484-5c8a-11e5-942f-416dfe1b2a20.png)

**Closed by antw** 2015-09-16 14:55 UTC
Labels: Bug
