### ISSUE TITLE
Secondary network pops back to default settings when viewing the heat-load

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1182] opened 2016-07-05 13:42 UTC
When the settings of the secondary network of the heat asset list are changed or types are added, the settings will go back to the default settings when the heat load is viewed.

**Comment by antw** [comment] 2016-07-05 13:55
Is this when you hit the "Save all and view heat-load" button? If so, this would be a duplicate of #1178.

The blue "Save" button should work until we have that fixed.

**Comment by ThomBuijs** [comment] 2016-07-05 14:31
It is for both buttons. If I press the blue button first and then the green one, it will still pop back to default settings.

**Comment by ChaelKruip** [comment] 2016-07-06 10:23
I can reproduce this as follows:
1. add new line in secondary network list
2. press 'save'
3. refresh page -> back to the default

**Comment by ChaelKruip** [comment] 2016-07-08 14:58
Assigning @grdw

**Comment by grdw** [comment] 2016-07-12 12:13
This problem is fixed together with https://github.com/quintel/etmoses/pull/1241

**Closed by grdw** 2016-07-12 12:13 UTC
Labels: Bug
