### ISSUE TITLE
Changing concurrency of EV to minimum also changes number of Households space/water heater combined network gas

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1383] opened 2016-08-22 09:25 UTC
When I change the concurrency of my EV's from maximum to minimum, ETMoses also changes the number of Households space/water heater combined network gas. However the units for the heating remains the original value (before changing concurrency) or is set to zero. I use this [LES](https://moses.energytransitionmodel.com/testing_grounds/537) for minimum EV concurrency and this is the [LES](https://moses.energytransitionmodel.com/testing_grounds/536) with maximum EV concurrency, so before I toggled the concurrency button.

Because of the weird amount of Households space/water heater combined network gas, the LES cannot be calculated. Is this a known issue?

**Comment by ChaelKruip** [comment] 2016-08-23 07:58
Closing as this is a duplicate of https://github.com/quintel/etmoses/issues/1145

**Closed by ChaelKruip** 2016-08-23 07:58 UTC
Labels: Bug
