### ISSUE TITLE
It seems like the gas charts do not add up

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1032] opened 2016-06-02 12:35 UTC
![image](https://cloud.githubusercontent.com/assets/104830/15744825/9d621930-28ce-11e6-9764-7108d28b326f.png)

Left chart says the following for more than 50% of the time:

* 4 bar: 6.71 kW
* 8 bar: 1.57 kW
* 40 bar: 1 kw

But the right hand chart says:
* almost no kWh from 4 to 8 bar, but judging from the left chart, this cannot be true
* no kWh from 8 to 40, but judging from the left chart, this cannot be true

**Comment by ChaelKruip** [comment] 2016-06-02 12:49
The weird asymmetry and inconsistency stems from the fact that the gas-connectors still have temporary constraints right @antw?. The constraint for the 0.125 - 4 bar is such that there is a huge deficit (shown in a creamy colour). In reality the constraints for demand are not very relevant (always very much larger than needed) so we probably should set them to 'infinite' to make these charts look more realistic.

Assigning @antw

**Comment by antw** [comment] 2016-06-02 13:57
> In reality the constraints for demand are not very relevant (always very much larger than needed) so we probably should set them to 'infinite' to make these charts look more realistic.

I'm in the process of grabbing a copy of the production load curves so that I may test this LES out for myself. I do believe you're correct about the 0.125 - 4 bar constraint being the limiting factor.

Maybe #965 will resolve this by removing `low_to_high` attributes from connectors. I'll check that out now.

**Comment by ChaelKruip** [comment] 2016-06-02 14:05
> Maybe #965 will resolve this by removing low_to_high attributes from connectors. I'll check that out now.

Sounds good!

**Comment by antw** [comment] 2016-06-02 14:54
> Maybe #965 will resolve this by removing low_to_high attributes from connectors. I'll check that out now.

I wasn't thinking straight when I wrote that. Removing `low_to_high` attributes from connectors has no effect, because the problem is an excess of demand.

The asymmetry between the different pressure layers is entirely due to insufficient infrastructure capacity at each level. If I increase the capacity at each level 100x, the chart looks like this:

![screen shot 2016-06-02 at 15 44 43](https://cloud.githubusercontent.com/assets/4383/15749064/f9506a08-28d8-11e6-823e-9664ce16d3dd.png)

If I remove *all* connectors – which are the limiting asset in flow from one pressure-level to another – that chart looks like:

![screen shot 2016-06-02 at 15 46 58](https://cloud.githubusercontent.com/assets/4383/15749145/4ed69de4-28d9-11e6-9964-f69a41dd6578.png)

> so we probably should set them to 'infinite' to make these charts look more realistic.

I think what you're suggesting is to remove the capacity attribute entirely from connectors so that only compressors have a capacity?

**Comment by ChaelKruip** [comment] 2016-06-02 14:59
> I think what you're suggesting is to remove the capacity attribute entirely from connectors so that only compressors have a capacity?

That's a far more eloquent way to put in words what I actually tried to convey, yes.

**Comment by antw** [comment] 2016-06-02 18:34
Closed by #965 and db550df9.

**Closed by antw** 2016-06-02 18:34 UTC
Labels: Bug
